static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 3080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: HTTP1
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/mg"
                route:
                  prefix_rewrite: "/mg/"
                  cluster: mg_jekyll
              - match:
                  prefix: "/mg/"
                route:
                  cluster: mg_jekyll
              - match:
                  prefix: "/node-play"
                route:
                  prefix_rewrite: "/node-play/"
                  cluster: node-play_jekyll
              - match:
                  prefix: "/node-play/"
                route:
                  cluster: node-play_jekyll
              - match:
                  prefix: "/"
                route:
                  cluster: root_jekyll
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: mg_jekyll
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 10001
  - name: node-play_jekyll
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 10002
  - name: root_jekyll
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 10000
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 18081




