description: > # this means to ignore newlines until "baseurl:"
  This is a documentation site.
title: Doc Template
logo: https://mediagoom.com/img/mediagoom.png
twitter: mediagoom
github: mediagoom
facebook: mediagoom

